baseURL = "https://dongkhaehaughty.xyz/"
languageCode = 'en-us'
title = "Let's Tilt  Windmills"
theme = 'color-your-world'

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 2
